pipeline {
    
    agent {
    node { label 'mvn' }
    } 
    
    stages {
             
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                
                sh ' sudo chmod +x ./jenkins/scripts/deliver.sh  &&  ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
