pipeline {
    
    environment {
        
     ImageRegistry_Username="${param.ImageRegistry_Username}"
     ImageRegistry_Password="${param.ImageRegistry_Password}"
     Nexus_URL="${param.Nexus_URL}"
        
    }
    agent {
    node { label 'mvn' }
    } 
    
    stages {
             
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Docker package') {
            steps {
                
                sh '''
                     sudo docker build . -t ${Nexus_URL}/demo-mvn:$BUILD_NUMBER && \
                     sudo docker login -u ${ImageRegistry_Username} -p ${ImageRegistry_Password}  ${Nexus_URL}  && \
                     sudo docker push  ${Nexus_URL}/demo-mvn:$BUILD_NUMBER
                  '''
            }
        }
        
        stage('Helm Chart Deploy')
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
            steps {
               sh 'helm upgrade -i mvn-app helm-manifests/  --set image.tag=$BUILD_NUMBER'
            }
    }
}
